---
# yamllint disable rule:line-length
- name: 'Live API test | verify | live API extraction successful'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Live API test | verify | find extracted archive'
      ansible.builtin.find:
        paths: '/opt/forgejo'
        file_type: 'directory'
        use_regex: true
        patterns:
          - '.*forgejo-.*'  # version will change with 'latest'
        recurse: false
      register: _test_codeberg_extracted_archives

    - name: 'Live API test | verify | archive extracted successfully'
      ansible.builtin.assert:
        that: _test_codeberg_extracted_archives.files | length == 1
        success_msg: '1 repo directory found.'
        fail_msg: '0 or multiple repo directories found. Should be 1.'

    - name: 'Live API test | verify | query README.md'
      ansible.builtin.stat:
        path: '{{ _test_codeberg_extracted_archives.files[0].path }}/README.md'
      register: _test_codeberg_live_removed_readme

    - name: 'Live API test | verify | assert README.md removed'
      ansible.builtin.assert:
        that:
          - not _test_codeberg_live_removed_readme.stat.exists
        fail_msg: 'README.md not removed.'
