---
# yamllint disable rule:line-length
# Role variable returned variables are scoped to the current play only (e.g.
# converge.yml) and must be tested between each application of the role. Test
# these values while converging versus verify.yml (where scoping will prevent)
# testing these values.
- name: 'Extract delete migration | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Extract delete migration | converge | apply r_pufky.srv.Codeberg (v1.0.0)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.codeberg'
      vars:
        codeberg_repo_archive_type: 'tar.gz'
        codeberg_repo_owner: 'leetreleaser'
        codeberg_repo_repo: 'test-repo'
        codeberg_repo_release: 'latest'
        codeberg_file_owner: 'root'
        codeberg_file_group: 'root'
        codeberg_extract_dest: '/opt/test-repo-gz'
        codeberg_extract_symlink_target: '/opt/test-repo-gz/test-repo'
        codeberg_extract_extra_opts: '--strip-components=1'
        codeberg_extract_mode: 'a-st,o-rwx'
        codeberg_extract_remove_files:
          - 'README.md'
          - '.hidden_file'
        codeberg_extract_migrate_files: ['config/db/db_skeleton_file.db']

    - name: 'Extract delete migration | converge | add non-repo directory'
      ansible.builtin.file:
        path: '/opt/test-repo-gz/this_dir_should_not_be_removed'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'

    - name: 'Extract delete migration | converge | add non-repo directory'
      ansible.builtin.file:
        path: '/opt/test-repo-gz/this_file_should_not_be_removed'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'touch'

- name: 'Extract delete migration | converge | migrate data'
  hosts: 'codeberg-debian-12-extract_delete_migration'
  gather_facts: false
  tasks:
    - name: 'Extract delete migration | converge | apply r_pufky.srv.Codeberg (v1.0.1)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.codeberg'
      vars:
        codeberg_repo_archive_type: 'tar.gz'
        codeberg_repo_owner: 'leetreleaser'
        codeberg_repo_repo: 'test-repo'
        codeberg_repo_release: 'latest'
        codeberg_file_owner: 'root'
        codeberg_file_group: 'root'
        codeberg_extract_dest: '/opt/test-repo-gz'
        codeberg_extract_symlink_target: '/opt/test-repo-gz/test-repo'
        codeberg_extract_extra_opts: '--strip-components=1'
        codeberg_extract_mode: 'a-st,o-rwx'
        codeberg_extract_remove_files:
          - 'README.md'
          - '.hidden_file'
        codeberg_extract_migrate_files:
          - 'config/db/db_skeleton_file.db'
          - 'non_existing_file_should_be_skipped_no_errors'
          - 'nested_migration'
        codeberg_extract_delete_old_versions: true

- name: 'Extract delete migration | converge | no migration'
  hosts: 'codeberg-debian-12-extract_delete_migration-no-keep'
  gather_facts: false
  tasks:
    - name: 'Extract delete migration | converge | apply r_pufky.srv.Codeberg (v1.0.1)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.codeberg'
      vars:
        codeberg_repo_archive_type: 'tar.gz'
        codeberg_repo_owner: 'leetreleaser'
        codeberg_repo_repo: 'test-repo'
        codeberg_repo_release: 'latest'
        codeberg_file_owner: 'root'
        codeberg_file_group: 'root'
        codeberg_extract_dest: '/opt/test-repo-gz'
        codeberg_extract_symlink_target: '/opt/test-repo-gz/test-repo'
        codeberg_extract_extra_opts: '--strip-components=1'
        codeberg_extract_mode: 'a-st,o-rwx'
        codeberg_extract_remove_files:
          - 'README.md'
          - '.hidden_file'
        codeberg_extract_delete_old_versions: true
