---
###############################################################################
# Codeberg REST API
###############################################################################
# TODO(sync): Keep features in sync with ansible_github.
#
# Reference:
# * https://codeberg.org/api/swagger

# Last time Codeberg options were validated against a default configuration.
codeberg_role_validate_date: '2024-06-22'
codeberg_role_validate_release: 'bookworm'

# Role checked against this version of the API.
codeberg_role_api_version: 'https://codeberg.org/api/v1'

# Codeberg API base URL.
codeberg_role_release_url_base: 'https://codeberg.org/api/v1/repos'

###############################################################################
# APT Packages
###############################################################################

codeberg_role_packages:
  - 'ca-certificates'  # SSL support for ansible.builtin.get_url.
  - 'unzip'  # zip archives.
  - 'xz-utils'  # xz archives.

codeberg_role_testing_packages:
  - 'rsync'  # ansible.posix.synchronize (testing local archive copy).
